on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install ts-node @prisma/client
      - run: ls -al ./prisma/
      - run: pnpx ts-node ./prisma/script.ts